module View.FindPlaces exposing (findPlacesSection)

import Html exposing (..)
import Html.Attributes exposing (..)
import Model.Main exposing (..)

findPlacesSection : Html Msg
findPlacesSection =
    section [ class "main-block" ]
        [ div [ class "container" ]
            [ div [ class "row justify-content-center" ]
                [ div [ class "col-md-5" ]
                    [ div [ class "styled-heading" ]
                        [ h3 []
                            [ text "What do you need to find?" ]
                        ]
                    ]
                ]
            , div [ class "row" ]
                [ div [ class "col-md-4" ]
                    [ div [ class "find-place-img_wrap" ]
                        [ div [ class "grid" ]
                            [ figure [ class "effect-ruby" ]
                                [ img [ src "images/find-place1.jpg", class "img-fluid", alt "img13" ]
                                    []
                                , figcaption []
                                    [ h5 []
                                        [ text "Nightlife" ]
                                    , p []
                                        [ text "385 Listings" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "col-md-4" ]
                    [ div [ class "row find-img-align" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place2.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Restaurants" ]
                                            , p []
                                                [ text "210 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "row" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place3.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Outdoors" ]
                                            , p []
                                                [ text "114 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "col-md-4" ]
                    [ div [ class "row find-img-align" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place4.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Hotels" ]
                                            , p []
                                                [ text "577 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "row" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place5.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Art & Culture" ]
                                            , p []
                                                [ text "79 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]