module View exposing (view)

import Browser
import Html exposing (..)
import Html.Attributes exposing (..)
import Model exposing (ALink, Model, Msg)


view : Model -> Browser.Document Msg
view model =
    { title = "UpSoRok"
    , body =
        [ navMenu
        , sliderSection
        , findPlacesSection
        , featuredPlacesSection
        , categoriesSection
        ]
    }


categoriesSection : Html Msg
categoriesSection =
    section [ class "main-block light-bg" ]
        [ div [ class "container" ]
            [ div [ class "row" ]
                [ div [ class "col-md-12" ]
                    [ div [ class "add-listing-wrap" ]
                        [ h2 []
                            [ text "Reach millions of People" ]
                        , p []
                            [ text "Add your Business infront of millions and earn 3x profits from our listing" ]
                        ]
                    ]
                ]
            , div [ class "row justify-content-center" ]
                [ div [ class "col-md-4" ]
                    [ div [ class "featured-btn-wrap" ]
                        [ a [ href "#", class "btn btn-danger" ]
                            [ span [ class "ti-plus" ] []
                            , text "ADD LISTING"
                            ]
                        ]
                    ]
                ]
            ]
        ]


featuredPlacesSection : Html Msg
featuredPlacesSection =
    section [ class "main-block light-bg" ]
        [ div [ class "container" ]
            [ div [ class "row justify-content-center" ]
                [ div [ class "col-md-5" ]
                    [ div [ class "styled-heading" ]
                        [ h3 []
                            [ text "Featured Places" ]
                        ]
                    ]
                ]
            , div [ class "row" ]
                [ div [ class "col-md-4 featured-responsive" ]
                    [ div [ class "featured-place-wrap" ]
                        [ a [ href "detail.html" ]
                            [ img [ src "images/featured1.jpg", class "img-fluid", alt "#" ]
                                []
                            , span [ class "featured-rating-orange" ]
                                [ text "6.5" ]
                            , div [ class "featured-title-box" ]
                                [ h6 []
                                    [ text "Burger & Lobster" ]
                                , p []
                                    [ text "Restaurant" ]
                                , span []
                                    [ text "•" ]
                                , p []
                                    [ text "3 Reviews" ]
                                , span []
                                    [ text "•" ]
                                , p []
                                    [ span []
                                        [ text "$$$" ]
                                    , text "$$"
                                    ]
                                , ul []
                                    [ li []
                                        [ span [ class "icon-location-pin" ]
                                            []
                                        , p []
                                            [ text "1301 Avenue, Brooklyn, NY 11230" ]
                                        ]
                                    , li []
                                        [ span [ class "icon-screen-smartphone" ]
                                            []
                                        , p []
                                            [ text "+44 20 7336 8898" ]
                                        ]
                                    , li []
                                        [ span [ class "icon-link" ]
                                            []
                                        , p []
                                            [ text "https://burgerandlobster.com" ]
                                        ]
                                    ]
                                , div [ class "bottom-icons" ]
                                    [ div [ class "closed-now" ]
                                        [ text "CLOSED NOW" ]
                                    , span [ class "ti-heart" ]
                                        []
                                    , span [ class "ti-bookmark" ]
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "col-md-4 featured-responsive" ]
                    [ div [ class "featured-place-wrap" ]
                        [ a [ href "detail.html" ]
                            [ img [ src "images/featured2.jpg", class "img-fluid", alt "#" ]
                                []
                            , span [ class "featured-rating-green" ]
                                [ text "9.5" ]
                            , div [ class "featured-title-box" ]
                                [ h6 []
                                    [ text "Joe’s Shanghai" ]
                                , p []
                                    [ text "Restaurant" ]
                                , span []
                                    [ text "•" ]
                                , p []
                                    [ text "3 Reviews" ]
                                , span []
                                    [ text "•" ]
                                , p []
                                    [ span []
                                        [ text "$$$" ]
                                    , text "$$"
                                    ]
                                , ul []
                                    [ li []
                                        [ span [ class "icon-location-pin" ]
                                            []
                                        , p []
                                            [ text "1301 Avenue, Brooklyn, NY 11230" ]
                                        ]
                                    , li []
                                        [ span [ class "icon-screen-smartphone" ]
                                            []
                                        , p []
                                            [ text "+44 20 7336 8898" ]
                                        ]
                                    , li []
                                        [ span [ class "icon-link" ]
                                            []
                                        , p []
                                            [ text "https://burgerandlobster.com" ]
                                        ]
                                    ]
                                , div [ class "bottom-icons" ]
                                    [ div [ class "closed-now" ]
                                        [ text "CLOSED NOW" ]
                                    , span [ class "ti-heart" ]
                                        []
                                    , span [ class "ti-bookmark" ]
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "col-md-4 featured-responsive" ]
                    [ div [ class "featured-place-wrap" ]
                        [ a [ href "detail.html" ]
                            [ img [ src "images/featured3.jpg", class "img-fluid", alt "#" ]
                                []
                            , span [ class "featured-rating" ]
                                [ text "3.2" ]
                            , div [ class "featured-title-box" ]
                                [ h6 []
                                    [ text "Tasty Hand-Pulled Noodles" ]
                                , p []
                                    [ text "Restaurant" ]
                                , span []
                                    [ text "•" ]
                                , p []
                                    [ text "3 Reviews" ]
                                , span []
                                    [ text "•" ]
                                , p []
                                    [ span []
                                        [ text "$$$" ]
                                    , text "$$"
                                    ]
                                , ul []
                                    [ li []
                                        [ span [ class "icon-location-pin" ]
                                            []
                                        , p []
                                            [ text "1301 Avenue, Brooklyn, NY 11230" ]
                                        ]
                                    , li []
                                        [ span [ class "icon-screen-smartphone" ]
                                            []
                                        , p []
                                            [ text "+44 20 7336 8898" ]
                                        ]
                                    , li []
                                        [ span [ class "icon-link" ]
                                            []
                                        , p []
                                            [ text "https://burgerandlobster.com" ]
                                        ]
                                    ]
                                , div [ class "bottom-icons" ]
                                    [ div [ class "open-now" ]
                                        [ text "OPEN NOW" ]
                                    , span [ class "ti-heart" ]
                                        []
                                    , span [ class "ti-bookmark" ]
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "row justify-content-center" ]
                [ div [ class "col-md-4" ]
                    [ div [ class "featured-btn-wrap" ]
                        [ a [ href "#", class "btn btn-danger" ]
                            [ text "VIEW ALL" ]
                        ]
                    ]
                ]
            ]
        ]


findPlacesSection : Html Msg
findPlacesSection =
    section [ class "main-block" ]
        [ div [ class "container" ]
            [ div [ class "row justify-content-center" ]
                [ div [ class "col-md-5" ]
                    [ div [ class "styled-heading" ]
                        [ h3 []
                            [ text "What do you need to find?" ]
                        ]
                    ]
                ]
            , div [ class "row" ]
                [ div [ class "col-md-4" ]
                    [ div [ class "find-place-img_wrap" ]
                        [ div [ class "grid" ]
                            [ figure [ class "effect-ruby" ]
                                [ img [ src "images/find-place1.jpg", class "img-fluid", alt "img13" ]
                                    []
                                , figcaption []
                                    [ h5 []
                                        [ text "Nightlife" ]
                                    , p []
                                        [ text "385 Listings" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "col-md-4" ]
                    [ div [ class "row find-img-align" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place2.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Restaurants" ]
                                            , p []
                                                [ text "210 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "row" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place3.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Outdoors" ]
                                            , p []
                                                [ text "114 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "col-md-4" ]
                    [ div [ class "row find-img-align" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place4.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Hotels" ]
                                            , p []
                                                [ text "577 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "row" ]
                        [ div [ class "col-md-12" ]
                            [ div [ class "find-place-img_wrap" ]
                                [ div [ class "grid" ]
                                    [ figure [ class "effect-ruby" ]
                                        [ img [ src "images/find-place5.jpg", class "img-fluid", alt "img13" ]
                                            []
                                        , figcaption []
                                            [ h5 []
                                                [ text "Art & Culture" ]
                                            , p []
                                                [ text "79 Listings" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]


sliderSection : Html Msg
sliderSection =
    section [ class "slider d-flex align-items-center" ]
        [ div [ class "container" ]
            [ div [ class "row d-flex justify-content-center" ]
                [ div [ class "col-md-12" ]
                    [ div [ class "slider-title_box" ]
                        [ div [ class "row" ]
                            [ div [ class "col-md-12" ]
                                [ div [ class "slider-content_wrap" ]
                                    [ h1 []
                                        [ text "Discover great businesses" ]
                                    , h5 []
                                        [ text "Let's uncover the best places to eat, drink, and shop nearest to you." ]
                                    ]
                                ]
                            ]
                        , div [ class "row d-flex justify-content-center" ]
                            [ div [ class "col-md-10" ]
                                [ Html.form [ class "form-wrap mt-4" ]
                                    [ div [ class "btn-group", attribute "role" "group", attribute "aria-label" "Basic example" ]
                                        [ input [ type_ "text", placeholder "What are your looking for?", class "btn-group1" ]
                                            []
                                        , input [ type_ "text", placeholder "New york", class "btn-group2" ]
                                            []
                                        , button [ type_ "submit", class "btn-form" ]
                                            [ span [ class "icon-magnifier search-icon" ] []
                                            , text "SEARCH"
                                            , i [ class "pe-7s-angle-right" ]
                                                []
                                            ]
                                        ]
                                    ]
                                , div [ class "slider-link" ]
                                    [ a [ href "#" ]
                                        [ text "Browse Popular" ]
                                    , span [] [ text "or" ]
                                    , a [ href "#" ]
                                        [ text "Recently Added" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]


dropDownMenu : ALink -> Html Msg
dropDownMenu alink =
    a [ class "dropdown-item", href alink.link ] [ text alink.name ]


navMenuItem : String -> List ALink -> Html Msg
navMenuItem name alink =
    li [ class "nav-item dropdown" ]
        [ a [ class "nav-link", href "#", id "navbarDropdownMenuLink", attribute "data-toggle" "dropdown", attribute "aria-haspopup" "true", attribute "aria-expanded" "false" ]
            [ text name
            , span [ class "icon-arrow-down" ] []
            ]
        , div [ class "dropdown-menu", attribute "aria-labelledby" "navbarDropdownMenuLink" ]
            (List.map dropDownMenu alink)
        ]


navBarNav : Html Msg
navBarNav =
    div [ class "navbar navbar-expand-lg navbar-light" ]
        [ a [ class "navbar-brand", href "index.html" ] [ text "UpSoRok" ]
        , button [ class "navbar-toggler", type_ "button", attribute "data-toggle" "collapse", attribute "data-target" "#navbarNavDropdown", attribute "aria-controls" "navbarNavDropdown", attribute "aria-expanded" "false", attribute "aria-label" "Toggle navigation" ]
            [ span [ class "icon-menu" ] [] ]
        , div [ class "collapse navbar-collapse justify-content-end", id "navbarNavDropdown" ]
            [ ul [ class "navbar-nav" ]
                [ navMenuItem "Reviews"
                    [ ALink "#" "Our Reviews"
                    , ALink "#" "Their Reviews"
                    , ALink "#" "Your Reviews"
                    ]
                , navMenuItem "Write"
                    [ ALink "#" "Your Review"
                    , ALink "#" "Corrections"
                    , ALink "#" "Random Thoughts"
                    ]
                , navMenuItem "Apps"
                    [ ALink "#" "Menu"
                    , ALink "#" "Pics"
                    , ALink "#" "Related"
                    ]
                , li [ class "nav-item active" ]
                    [ a [ class "nav-link", href "#" ]
                        [ text "About" ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "nav-link", href "#" ]
                        [ text "Blog" ]
                    ]
                , li []
                    [ a [ href "#", class "btn btn-outline-light top-btn" ]
                        [ span [ class "ti-plus" ] []
                        , text "Login"
                        ]
                    ]
                ]
            ]
        ]


navMenu : Html Msg
navMenu =
    div [ class "nav-menu" ]
        [ div [ class "bg transition" ]
            [ div [ class "container-fluid fixed" ]
                [ div [ class "row" ]
                    [ div [ class "col-md-12" ]
                        [ navBarNav ]
                    ]
                ]
            ]
        ]
